rejestrapp/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "rejestrapp"
urlpatterns = [
    path("", views.UserspaceView.as_view(), name="userspace"),
    path(
        "login/",
        views.NoRepeatLoginView.as_view(template_name="rejestrapp/login.html"),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "account-activation/<slug:token>/",
        views.AccountActivationView.as_view(),
        name="account_activation",
    ),
    path(
        "account-activation-cancelling/<slug:token>/",
        views.AccountActivationCancelView.as_view(),
        name="account_activation_cancelling",
    ),
    path("new-register/", views.NewRegisterView.as_view(), name="new_register"),
    path("register/<int:register_id>/", views.RegisterView.as_view(), name="register"),
    path(
        "register/<int:register_id>/new-transaction/",
        views.NewTransactionView.as_view(),
        name="new_transaction",
    ),
    path(
        "register/<int:register_id>/new-easy-transaction/",
        views.NewEasyTransactionView.as_view(),
        name="new_easy_transaction",
    ),
    path(
        "register/<int:register_id>/transaction/<int:group_transaction_id>/",
        views.TransactionVoteView.as_view(),
        name="transaction_vote",
    ),
    path("invite/<int:register_id>/", views.InviteView.as_view(), name="invite"),
    path(
        "invite/<int:register_id>/accept/",
        views.InviteAcceptView.as_view(),
        name="invite_accept",
    ),
    path(
        "invite/<int:register_id>/reject/",
        views.InviteRejectView.as_view(),
        name="invite_reject",
    ),
]

rejestrskladek/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("rejestrapp.urls")),
]

rejestrapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms.widgets import NumberInput, TextInput

from .models import SignupToken


class MustNameNewTransactionWidget(TextInput):
    """
    Widget for displaying an extra validation message
    about the name of a new transaction.
    """

    template_name = "rejestrapp/must_name_new_transaction_widget.html"


class NewTransactionFormBase(forms.Form):
    """
    This class is used as a base for dynamically creating
    manual transaction form classes. Code that derives form classes
    from it should add fields for values for users.
    """

    transaction_name = forms.CharField(
        label="Nazwa transakcji", max_length=128, widget=MustNameNewTransactionWidget
    )


class ValidatedExpenseWidget(NumberInput):
    """
    Widget for displaying and extra validation message
    about the supplied value of the expense.
    """

    template_name = "rejestrapp/validated_expense_widget.html"


class NewEasyTransactionFormBase(forms.Form):
    """
    This class is used as a base for dynamically creating
    simplified transaction form classes. Code that derives form classes
    from it should add fields for values for users.
    """

    transaction_name = forms.CharField(
        label="Nazwa transakcji",
        max_length=128,
        widget=MustNameNewTransactionWidget,
        required=True,
    )
    expense = forms.FloatField(
        label="Ile wydano",
        min_value=0.0,
        step_size=0.01,
        widget=ValidatedExpenseWidget,
        required=True,
    )


class TransactionVoteForm(forms.Form):
    """
    Form for voting on a transaction.
    """

    supports = forms.BooleanField(
        label="Zgadzasz sie na tą transakcje?", required=False
    )
    wants_remove = forms.BooleanField(
        label="Chcesz anulować tą transakcje?", required=False
    )


class RequiredFormSet(forms.BaseFormSet):
    """
    A formset with added functionality that prohibits
    empty values on fields.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = False
            form.use_required_attribute = True


class UserToNewRegisterForm(forms.Form):
    """
    A form to be used by the formset for adding users to a register.
    """

    username = forms.CharField(label="Nazwa użytkownika", max_length=150)


class NewRegisterNameForm(forms.Form):
    """
    A form that will be used by the formset for adding new users to a register.
    It holds the new register's name.
    """

    name = forms.CharField(label="Nazwa rejestru", max_length=128)


class TokenedUserCreationForm(UserCreationForm):
    """
    A form for signing up that requires a token to register.
    """

    signup_token = forms.CharField(
        label="Token Rejestracyjny",
        required=True,
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "off"}),
        help_text="Wklej token rejestracyjny",
    )

    def validate_token(self):
        form_token = self.cleaned_data.get("signup_token")
        token = SignupToken.objects.filter(pk=form_token).first()
        if token is None or token.used_up:
            error = ValidationError("Niepoprawny token", code="invalid_token")
            self.add_error("signup_token", error)

    def clean(self):
        self.validate_token()
        return super().clean()


class UserCreationFormWithEmail(UserCreationForm):
    email = forms.EmailField(
        label="E-mail",
        help_text=" ",
        required=True,
        widget=forms.EmailInput(),
        max_length=254,
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def validate_email_unique(self):
        form_email = self.cleaned_data.get("email").lower()
        email_query = User.objects.filter(email=form_email)

        if email_query.count() != 0:
            token_query = SignupToken.objects.filter(email=form_email)
            if token_query.count() == 0:
                error = ValidationError(
                    "Istnieje już konto z takim e-mailem", code="used_email"
                )
                self.add_error("email", error)

rejestrapp/views.py
import datetime
import hashlib
import random
import secrets
import requests
import typing
from django.conf import settings
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.db.models import F
from django.forms import formset_factory
from django.http import HttpRequest, HttpResponseRedirect
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView, View
from django.shortcuts import get_object_or_404, redirect, render
from .forms import (
    NewRegisterNameForm,
    RequiredFormSet,
    TransactionVoteForm,
    UserCreationFormWithEmail,
    UserToNewRegisterForm,
)
from .models import (
    Debt,
    GroupTransaction,
    IndividualsTransaction,
    Register,
    SignupToken,
)
from .utils import (
    account_activation_link_validation,
    check_for_errors_in_invite_view,
    check_if_can_be_viewed,
    dont_be_logged_in,
    generate_new_easy_transaction_form_class,
    generate_new_transaction_form_class,
    gr_to_zl,
    render_error_page,
)


class UserspaceView(View):
    """
    This is a user's 'main menu'. Here they have a list of their registers
    as well as their invitations.
    """

    http_method_names = ["get", "options"]

    def get(self, request: HttpRequest, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(reverse("rejestrapp:login"))
        accepted_registers = []
        accepted_invites = []
        not_accepted_invites = []
        for register in Register.objects.filter(users=request.user).order_by("name"):
            if register.all_accepted:
                accepted_registers.append(register)
            else:
                debt_set = register.debt_set
                if debt_set.get(user=request.user.pk).accepted:
                    accepted_invites.append(
                        (
                            register,
                            debt_set.filter(accepted=True).count(),
                            debt_set.count(),
                        )
                    )
                else:
                    not_accepted_invites.append(register)
        return render(
            request,
            "rejestrapp/userspace.html",
            {
                "accepted_registers": accepted_registers,
                "accepted_invites": accepted_invites,
                "not_accepted_invites": not_accepted_invites,
            },
        )


@dont_be_logged_in
class NoRepeatLoginView(LoginView):
    """
    The standart LoginView with an additional decorator
    that prevents logged-in users from accessing it.
    """

    pass


@dont_be_logged_in
class SignUpView(CreateView):
    """
    View for creating new users. When someone creates an account,
    they are automatically logged in. The decorator prevents
    logged-in users from accessing it.
    """

    form_class = UserCreationFormWithEmail
    # success_url = reverse_lazy("rejestrapp:userspace")
    template_name = "rejestrapp/signup.html"

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            email = form.cleaned_data["email"].lower()
            previous_token_query = SignupToken.objects.filter(email=email)
            if previous_token_query.count() != 0:
                return render_error_page(
                    request,
                    "Ten adres e-mail został niedawno użyty w próbie "
                    "utworzenia konta. Sprawdź swoją skrzynkę.",
                    400,
                    reverse("rejestrapp:signup"),
                )
            new_user = form.save(commit=False)
            new_user.is_active = False
            new_user.email = email
            new_user.save()
            new_user.refresh_from_db()
            self.object = new_user
            token = secrets.token_hex(32)
            hashed_token = hashlib.sha256(bytes(token, "utf-8")).hexdigest()
            SignupToken.objects.create(pk=hashed_token, email=email)
            email_api_req_headers = {
                "Content-Type": "application/json",
                "X-Requested-With": "XMLHttpRequest",
                "User-Agent": "RejestrSkladek",
                "Authorization": f"Bearer {settings.EMAIL_API_KEY}",
            }
            message_template = loader.get_template("rejestrapp/activation_email.html")
            message_html = message_template.render(
                {"nazwa": new_user.username, "token": token}, request
            )
            email_api_message = {
                "from": {
                    "email": settings.EMAIL_API_EMAIL_ADDRESS,
                    "name": "Rejestr Składek",
                },
                "to": [
                    {
                        "email": email,
                        "name": new_user.username,
                    }
                ],
                "subject": "Dokończ tworzenie konta w Rejestrze Składek",
                "html": message_html,
            }
            email_api_response = requests.post(
                "https://api.mailersend.com/v1/email",
                headers=email_api_req_headers,
                json=email_api_message,
            )
            if not email_api_response.ok:
                return render_error_page(
                    request,
                    "Nie udało się dotrzeć do podanego adresu e-mail",
                    400,
                    reverse("rejestrapp:signup"),
                )

            return render(
                request,
                "rejestrapp/go_to_email.html",
                {"back": reverse("rejestrapp:login")},
            )
        else:
            return self.form_invalid(form)


class AccountActivationView(View):
    """
    View for handling the clicking of the activation link.
    It changes the particular account's 'is_active' to True.
    """

    http_method_names = ["get", "options"]

    @account_activation_link_validation
    def get(self, request: HttpRequest, *args, **kwargs):
        activated_user = kwargs["account_activation_link_validation__user"]
        activated_user.is_active = True
        activated_user.save()
        return HttpResponseRedirect(reverse("rejestrapp:login"))


class AccountActivationCancelView(View):
    """
    View for canceling account creation. Accessed from
    the activation email.
    """

    http_method_names = ["get", "options"]

    @account_activation_link_validation
    def get(self, request: HttpRequest, *args, **kwargs):
        cancelled_user = kwargs["account_activation_link_validation__user"]
        cancelled_user.delete()
        return HttpResponseRedirect(reverse("rejestrapp:signup"))


@check_if_can_be_viewed
class RegisterView(LoginRequiredMixin, View):
    """
    View for displaying a register's data in a table.
    """

    http_method_names = ["get", "options"]

    def get(self, request: HttpRequest, *args, **kwargs):
        register = kwargs["check_if_can_be_viewed__register"]
        debts_for_display = []
        for debt in register.debt_set.all().order_by("user__username"):
            debts_for_display.append(
                {"name": debt.user.username, "balance": gr_to_zl(debt.balance)}
            )
        return render(
            request,
            "rejestrapp/register.html",
            {
                "debts": debts_for_display,
                "register": register,
                "transactions": GroupTransaction.objects.filter(
                    debts__register__pk=register.pk
                )
                .distinct()
                .order_by("is_settled", "-settle_date", "-init_date"),
                "back": reverse("rejestrapp:userspace"),
            },
        )


@check_if_can_be_viewed
class NewTransactionView(LoginRequiredMixin, View):
    """
    View for initiating and processing manual transactions.
    When accessed by GET, it displays a form with a field
    for every user in a register where values should be supplied.
    When POSTed to, it checks whether the values add up to zero
    and creates a new GroupTransaction object if they do.
    """

    http_method_names = ["get", "post", "options"]

    def get(self, request: HttpRequest, *args, **kwargs):
        register = kwargs["check_if_can_be_viewed__register"]
        form_class = generate_new_transaction_form_class(
            register.users.all().order_by("username")
        )
        form = form_class()

        return render(
            request,
            "rejestrapp/new_transaction.html",
            {
                "register": register,
                "form": form,
                "back": reverse(
                    "rejestrapp:register", kwargs={"register_id": register.pk}
                ),
            },
        )

    def post(self, request: HttpRequest, *args, **kwargs):
        register = kwargs["check_if_can_be_viewed__register"]
        form_class = generate_new_transaction_form_class(
            register.users.all().order_by("username")
        )
        form = form_class(request.POST)

        if form.is_valid():
            amount_sum = 0
            for k, v in form.cleaned_data.items():
                if k == "transaction_name":
                    continue
                amount_sum += round(v * 100)
            if amount_sum != 0:
                return render_error_page(
                    request,
                    "Wpisane wartości mają dodawać sie do zera",
                    422,
                    reverse(
                        "rejestrapp:new_transaction",
                        kwargs={"register_id": register.pk},
                    ),
                )
            group_transaction = GroupTransaction.objects.create(

rejestrapp/templates/rejestrapp/activation_email.html
<h1>Rejestr Składek</h1>
<p>Aby dokończyć aktywację konta o nazwie <b>{{ nazwa }}</b> wciśnij przycisk "Aktywuj".</p>
<p>Jeśli nie chcesz tego robić, wciśnij przycisk "Przerwij".</p>
<h4><a href="https://{{ request.get_host }}{% url 'rejestrapp:account_activation' token=token %}">Aktywuj</a></h4>
<h4><a href="https://{{ request.get_host }}{% url 'rejestrapp:account_activation_cancelling' token=token %}">Przerwij</a></h4>

rejestrapp/templates/rejestrapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'rejestrapp/style.css' %}" rel="stylesheet">
    <title>{% block title %}Rejestr Składek{% endblock %}</title>
    {% block head_additions %}{% endblock %}
  </head>
  <body>
    <div id="top_bar">
      {% if back %}
      <div id="back">
        <p><a href="{{ back }}">Wstecz</a></p>
      </div>
      {% endif %}
      {% if user.is_authenticated %}
      <div id="account">
        <p id="logged_in_as">Zalogowano jako {{ user.username }}</p>
        <form action="{% url 'rejestrapp:logout' %}" method="post">
          {% csrf_token %}
          <input id="logout_button" type="submit" value="Wyloguj">
        </form>
      </div>
      {% endif %}
    </div>
    <div id="content">
      {% block content %}
      <p>This is the default page template.</p>
      {% endblock %}
    </div>
  </body>
</html>

rejestrapp/templates/rejestrapp/error.html
{% extends "rejestrapp/base.html" %}

{% block title %}Błąd{% endblock %}

{% block content %}
<h1>BŁĄD</h1>
<p>{{ error_message }}</p>
{% endblock %}

rejestrapp/templates/rejestrapp/go_to_email.html
{% extends "rejestrapp/base.html" %}

{% block title %}Zajrzyj do skrzynki{% endblock %}

{% block content %}
<h1>Sprawdź swoją skrzynkę</h1>
<p>Aby dokończyć tworzenie konta, otwórz wiadomość, którą zaraz otrzymasz na maila.</p>
{% endblock %}

rejestrapp/templates/rejestrapp/invite.html
{% extends "rejestrapp/base.html" %}

{% block title %}Zaproszenie do {{ register.name }}{% endblock %}

{% block content %}
<div class="centered">
  <h1>Zaproszenie do rejestru &quot;{{ register.name }}&quot;</h1>
</div>
<div id="invite_form_div">
  <form method="post" action="{% url 'rejestrapp:invite_reject' register.pk %}">
    {% csrf_token %}
    <input id="reject_invitation" class="invite_buttons" type="submit" value="Odrzuć">
  </form>
  <form method="post" action="{% url 'rejestrapp:invite_accept' register.pk %}">
    {% csrf_token %}
    <input id="accept_invitation" class="invite_buttons" type="submit" value="Dołącz">
  </form>
</div>
{% endblock %}

rejestrapp/templates/rejestrapp/login.html
{% extends "rejestrapp/base.html" %}

{% block title %}Logowanie{% endblock %}

{% block login_button %}{% endblock %}

{% block content %}
<p><a href="{% url 'rejestrapp:signup' %}">Załóż konto</a></p>
<br>

{% if form.errors %}
<p>Podano niepoprawne dane logowania. Spróbuj ponownie.</p>
{% endif %}

{% if next %}
  <p>Zaloguj się, aby dostać się do tej strony</p>
{% endif %}

<form method="post" action="{% url "rejestrapp:login" %}">
{% csrf_token %}
<table>
<tr>
    <td>Nazwa użytkownika</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>Hasło</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="Zaloguj">
<input type="hidden" name="next" value="{{ next }}">
</form>
{% endblock %}

rejestrapp/templates/rejestrapp/must_name_new_transaction_widget.html
{% include "django/forms/widgets/input.html" %}<p id="must_name_new_transaction" hidden>Transakcja musi mieć jakąś nazwę</p>

rejestrapp/templates/rejestrapp/new_easy_transaction.html
{% extends "rejestrapp/base.html" %}
{% load static %}

{% block head_additions %}
<script src="{% static "rejestrapp/utils.js" %}"></script>
<script src="{% static "rejestrapp/new_easy_transaction_validation.js" %}"></script>
{% endblock %}

{% block title %}Nowa uproszczona transakcja{% endblock %}

{% block content %}
<h1>{{ register.name }}</h1>
<form id="new_transaction_form" method="post" action="{% url 'rejestrapp:new_easy_transaction' register.pk %}">
  {% csrf_token %}
  {{ form }}
</form>
<p id="invalid_value" hidden>Podaj poprawne wartości pieniędzy.</p>
<p id="not_adding_up">Suma dołożeń powinna się równać wydatkowi.</p>
<button id="new_transaction_button">Rozpocznij nową transakcję</button>
{% endblock %}

rejestrapp/templates/rejestrapp/new_register.html
{% extends "rejestrapp/base.html" %}
{% load static %}

{% block head_additions %}
<script>
let form_count = {{formset.total_form_count}};
window.onload = () => {
  const users_form = document.getElementById("forms");
  const total_forms = document.getElementById("id_usernames-TOTAL_FORMS");
  document.getElementById("add_form").onclick = () => {
    const template = document.createElement("template");
    template.innerHTML = "{{formset.empty_form|escapejs}}".replace(/__prefix__/g, form_count);
    users_form.appendChild(template.content.firstChild);
    form_count++;
    total_forms.value = form_count;
  };
};
</script>
{% endblock %}

{% block title %}Nowy rejestr{% endblock %}

{% block content %}
<h1>Tworzenie nowego rejestru</h1>
<form method="post" action="{% url 'rejestrapp:new_register' %}">
  {% csrf_token %}
  {{ formset.management_form }}
  {{ name_form }}
  <div id="forms">
    <label for="id_ro_you">Nazwa użytkownika:</label>
    <input type="text" id="id_ro_you" name="ro_you" value="{{ user.username }}" readonly>
    {% for form in formset.forms %}
    {{ form }}
    {% endfor %}
  </div>
  <button type="button" id="add_form">Więcej osób</button>
  <br><br>
  <input type="submit" value="Stwórz rejestr">
</form>
{% endblock %}

rejestrapp/templates/rejestrapp/new_transaction.html
{% extends "rejestrapp/base.html" %}
{% load static %}

{% block head_additions %}
<script src="{% static "rejestrapp/utils.js" %}"></script>
<script src="{% static "rejestrapp/new_transaction_validation.js" %}"></script>
{% endblock %}

{% block title %}Nowa manualna transakcja{% endblock %}

{% block content %}
<h1>{{ register.name }}</h1>
<form id="new_transaction_form" method="post" action="{% url 'rejestrapp:new_transaction' register.pk %}">
  {% csrf_token %}
  {{ form }}
</form>
<p id="invalid_value" hidden>Podaj poprawne wartości pieniędzy.</p>
<p id="not_adding_to_zero">Suma wartości powinna wynosić 0.</p>
<button id="new_transaction_button">Rozpocznij nową transakcję</button>
{% endblock %}

rejestrapp/templates/rejestrapp/register.html
{% extends "rejestrapp/base.html" %}

{% block title %}{{ register.name }}{% endblock %}

{% block content %}
<h1>{{ register.name }}</h1>
<table>
  <thead>
    <tr>
      <td>Imię</td>
      <td>Stan konta</td>
    </tr>
  </thead>
  <tbody>
{% for debt in debts %}
    <tr>
      <td>{{ debt.name }}</td>
      <td>{{ debt.balance }}</td>
    </tr>
{% endfor %}
  </tbody>
</table>
<p><a href="{% url 'rejestrapp:new_transaction' register.id %}">Nowa manualna transakcja</a></p>
<p><a href="{% url 'rejestrapp:new_easy_transaction' register.id %}">Nowa uproszczona transakcja</a></p>
<ul>
  {% for transaction in transactions %}
  <li><a href="{% url 'rejestrapp:transaction_vote' register.id transaction.id %}">{{ transaction.name }}</a>; {{ transaction.init_date }}; {% if transaction.is_settled %}Przyjęte w dniu {{ transaction.settle_date }}{% else %}Narazie nieprzyjęte{% endif %}</li>
  {% endfor %}
</ul>
{% endblock %}

rejestrapp/templates/rejestrapp/transaction_vote.html
{% extends "rejestrapp/base.html" %}

{% block title %}Głosuj | {{ transaction_name }}{% endblock %}

{% block content %}
<h1>{{ register_name }}</h1>
<h3>{{ transaction_name }}</h3>
<table>
  <thead>
    <tr>
      <td>Imię</td>
      <td>
        {% if voting_allowed %}
        Obecny stan konta
        {% else %}
        Stan konta przed
        {% endif %}
      </td>
      <td>Stan konta po</td>
      <td>Zmiana</td>
      <td>Zgoda</td>
      <td>Chce usunąć</td>
    </tr>
  </thead>
  <tbody>
    {% for row in vote_table_rows %}
    <tr>
      <td>{{ row.indiv.debt.user.username }}</td>
      <td>{{ row.balance_before }}</td>
      <td>{{ row.balance_after }}</td>
      <td>{{ row.amount }}</td>
      <td>{% if row.indiv.supports %}&#x2705;{% else %}&#x274C;{% endif %}</td>
      <td>{% if row.indiv.wants_remove %}&#x2705;{% else %}&#x274C;{% endif %}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<br>
{% if voting_allowed %}
<form method="post" action="{% url 'rejestrapp:transaction_vote' register_id group_transaction_id %}">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Zmień zgody">
</form>
{% endif %}
{% endblock %}

rejestrapp/templates/rejestrapp/userspace.html
{% extends "rejestrapp/base.html" %}

{% block title %}Twoje rejestry{% endblock %}

{% block content %}
<h1>Rejestry, do których należysz</h1>
{% if accepted_registers or accepted_invites %}
<ul>
  {% for register in accepted_registers %}
  <li><a href="{% url 'rejestrapp:register' register.pk %}">{{ register }}</a></li>
  {% endfor %}
  {% for accepted_invite in accepted_invites %}
  <li>{{ accepted_invite.0 }}; {{ accepted_invite.1 }} na {{ accepted_invite.2 }} członków przyjęło zaproszenie</li>
  {% endfor %}
</ul>
{% else %}
<p>Brak</p>
{% endif %}
<br>
<p><a href="{% url 'rejestrapp:new_register' %}">Stwórz nowy rejestr</a></p>
<br>
<h3>Zaproszenia</h3>
{% if not_accepted_invites %}
<ul>
  {% for invite in not_accepted_invites %}
  <li>
    <div style="display: flex;">
      <p class="p_with_form">Zaproszenie do rejestru &quot;{{ invite }}&quot;</p>
      <button onclick="window.location.replace('{% url 'rejestrapp:invite' invite.id %}');">Odpowiedz</button>
    </div>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>Brak</p>
{% endif %}
{% endblock %}

rejestrapp/templates/rejestrapp/validated_expense_widget.html
{% include "django/forms/widgets/input.html" %}<p id="invalid_expense" hidden>Wpisz poprawny wydatek</p>